### ISSUE TITLE
2018 Wintax -> Sch A -> [37-39] Home mtg. int. from 1098 -> Must add description prior to entering values 

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#242]
**Client Name:**  
BARREY H. STAGGS, CPA

**Client ID:**  
87191

**Description:**  
Client states that prior year programs never forced a description prior to value entry and that descriptions are not necessary.

**Reproduce:**  
2018 Wintax -> Sch A -> [37-39] Home mtg. int. from 1098 -> Must add description prior to entering values 

**Data Location:**

**Comment by MHGray** [comment]
I believe he is referring to the overflow schedules. It doesn't make any sense to use an overflow schedule and not put in descriptions because that is specifically what it is designed for, to add details about specific items to an aggregate total. If he wants to just put in the amounts he should just total them and put them on the line itself.
