### ISSUE TITLE
2018 Wintax - AZ Return - Federal Adjusted Gross Income Incorrect, 'NotBound' Values Possibly at Play

### ISSUE THREAD

**Issue by twnathan** [TaxwareSupport/Issue-Reports#452]
**Client Name:**  
TAMARA @ ROBERT DUFOUR's Office

**Client ID:**  
20191

**Description:**  
![image](https://user-images.githubusercontent.com/44508876/54952397-1fe35880-4f03-11e9-8729-8d2def5a15d2.png)

![image](https://user-images.githubusercontent.com/44508876/54952458-45706200-4f03-11e9-9e23-85453f5b8e39.png)

Can't immediately see a reason why the AZ return would reject, but seeing as how it has something to do with a miscalculation of the FED AGI, and that the AZ FED AGI input screen has those "notBound" messages, it makes me wonder if that is what is throwing things off.

**Steps to Reproduce:**  

**Data Location:**
R:\Nathan\20191 - TAMARA @ ROBERT DUFOUR - AZ Reject

**Comment by DodgerDave** [comment]
The two other addition items that showed "notBound" were discontinued for 2018 and I have taken them off the menu. The error for the federal AGI and Arizona percentage was most likely caused by a change in the federal AGI and not going back into AZ.  Have them go into AZ and that should fix the validation errors.  No need to carry fed to state.
