### ISSUE TITLE
Wintax - AR - AR Direct Deposit Loop

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#719]
**Client Name:**  
487-86

**Client ID:**  
Jimmy

**Description:**  
Trying to leave this return while having direct deposit information is impossible. Seems to fix itself if I uncheck the choose optimum status button in Basic Information. In general, choosing no 
![image](https://user-images.githubusercontent.com/8196735/73407268-6f29b080-42ad-11ea-8361-eb7825a11175.png)

**Steps to Reproduce:**  
Use Data Provided -> Go into AR -> Try to leave AR while choosing yes on do you want to enter direct deposit. 

**Data Location:**
R:\Matt\ARDirectDepositLoop

**Comment by MTNielson** [comment]
Fixed.  But.  This happened because if MFJ they owed, but MFS same return they had a refund.  Since it calcs using both status's it was clearing the direct deposit when it saw that there was a balance due.
I had to move where it clears the direct deposit if no Refund to After it has done both calculations.
