### ISSUE TITLE
Wintax - Schedule A - Clearing the schedule A doesn't remove or zero out anything.

### ISSUE THREAD

**Issue by MHGray** [TaxwareSupport/Issue-Reports#99]
**Client Name:**  
Elizabeth

**Client ID:**  
99059

**Description:**  
Clearing the Schedule A from [88] Clear Forms and Schedules does not actually clear the form or remove the values in it. Meaning that if you had input something in there incorrectly and wanted to clear and start fresh you would have to manually go in and take out each value individually.

**Reproduce:**  
Go into Sch A and input 80000 into medical expenses to get an itemized deduction. Then try to clear forms and schedules

**Comment by MyNameIsDonovan** [comment]
Sch A has some weird stuff surrounding it... currently uses multiple flags to detimine calc/requirement
I'll revisit this for sometime in the future haha

**Comment by DodgerDave** [comment]
For most forms and schedules (88) to clear works since it turns of the forms flag and the variables are not stored if the flag is off.  It's different for Schedule A.  Starting in 2018 we save the Sch A variables no matter what.  I think we do this because some states can have the itemized deduction even if the standard is taken on the federal. There might have been another reason but I can't think of it.
